"""empty message

Revision ID: 2cbefd2d5a9a
Revises: 
Create Date: 2021-12-09 01:04:10.687811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbefd2d5a9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('subtitle', sa.String(length=140), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.Column('about_image', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=140), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('contact_subtitle', sa.String(length=140), nullable=True),
    sa.Column('about_subtitle', sa.String(length=140), nullable=True),
    sa.Column('feature_subtitle', sa.String(length=140), nullable=True),
    sa.Column('feature_paragraph', sa.Text(), nullable=True),
    sa.Column('faq_title', sa.String(length=140), nullable=True),
    sa.Column('faq_subtitle', sa.String(length=140), nullable=True),
    sa.Column('faq_paragraph', sa.String(length=140), nullable=True),
    sa.Column('testimonial_title', sa.String(length=140), nullable=True),
    sa.Column('testimonial_subtitle', sa.String(length=140), nullable=True),
    sa.Column('testimonial_paragraph', sa.String(length=140), nullable=True),
    sa.Column('team_title', sa.String(length=140), nullable=True),
    sa.Column('team_subtitle', sa.String(length=140), nullable=True),
    sa.Column('team_paragraph', sa.String(length=140), nullable=True),
    sa.Column('logo', sa.String(length=64), nullable=True),
    sa.Column('carousel_image_1', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_email'), 'about', ['email'], unique=True)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=140), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('amount', sa.Text(), nullable=False),
    sa.Column('features', sa.Text(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('faceboook', sa.String(length=140), nullable=True),
    sa.Column('instagram', sa.Integer(), nullable=True),
    sa.Column('twitter', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('web_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_feature')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('testimonial')
    op.drop_table('teams')
    op.drop_table('price')
    op.drop_table('faq')
    op.drop_index(op.f('ix_about_email'), table_name='about')
    op.drop_table('about')
    # ### end Alembic commands ###
