"""empty message

Revision ID: 65ebba74fcc8
Revises: 17b7269e57b4
Create Date: 2023-01-07 13:14:46.310735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ebba74fcc8'
down_revision = '17b7269e57b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('text2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('text3', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_feature', schema=None) as batch_op:
        batch_op.drop_column('text3')
        batch_op.drop_column('text2')
        batch_op.drop_column('text1')

    # ### end Alembic commands ###
