"""block and appearance moodules

Revision ID: 91198095914a
Revises: d4555864329a
Create Date: 2021-12-24 00:47:12.466012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91198095914a'
down_revision = 'd4555864329a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('block_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('title_color', sa.String(length=64), nullable=True),
    sa.Column('subtitle_color', sa.String(length=64), nullable=True),
    sa.Column('paragraph_color', sa.String(length=64), nullable=True),
    sa.Column('title_font', sa.String(length=64), nullable=True),
    sa.Column('subtitle_font', sa.String(length=64), nullable=True),
    sa.Column('paragraph_font', sa.String(length=64), nullable=True),
    sa.Column('title_size', sa.Integer(), nullable=True),
    sa.Column('subtitle_size', sa.Integer(), nullable=True),
    sa.Column('paragraph_size', sa.Integer(), nullable=True),
    sa.Column('bootstrap_class1', sa.String(length=64), nullable=True),
    sa.Column('bootstrap_class2', sa.String(length=64), nullable=True),
    sa.Column('bootstrap_class3', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appearance')
    op.drop_table('blocks')
    # ### end Alembic commands ###
