"""text fields

Revision ID: d4555864329a
Revises: 2cbefd2d5a9a
Create Date: 2021-12-15 19:46:31.468492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4555864329a'
down_revision = '2cbefd2d5a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('atext', sa.Text(), nullable=False))
    op.drop_column('about', 'text')
    op.add_column('web_feature', sa.Column('wtext', sa.Text(), nullable=False))
    op.drop_column('web_feature', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_feature', sa.Column('text', sa.TEXT(), nullable=False))
    op.drop_column('web_feature', 'wtext')
    op.add_column('about', sa.Column('text', sa.TEXT(), nullable=False))
    op.drop_column('about', 'atext')
    # ### end Alembic commands ###
